CREATE TABLE Sensor_info (
    model_id int GENERATED BY DEFAULT AS IDENTITY,
    model varchar(16) PRIMARY KEY,
    description varchar(255) NOT NULL
);
CREATE TABLE Sensor (
    sensor_id int GENERATED BY DEFAULT AS IDENTITY,
    name varchar(50) NOT NULL,
    serial_number int PRIMARY KEY,
    model varchar(16) REFERENCES Sensor_info(model),
    created_at date NOT NULL
);
CREATE TABLE Measurement (
    measurement_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    serial_number_sensor int REFERENCES Sensor(serial_number),
    temperature int NOT NULL CHECK(temperature BETWEEN -100 AND 100),
    humidity int NOT NULL CHECK(temperature BETWEEN 0 AND 100),
    weather varchar(20) NOT NULL,
    registrated_at date NOT NULL
);

DROP TABLE Measurement;
DROP TABLE Sensor;
DROP TABLE Sensor_info;

